// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPuBKuNBJG9SfbUs3Hiu7AlqyUgDrly6M',
    appId: '1:163576928903:web:b04e8e34f18a2dcab77622',
    messagingSenderId: '163576928903',
    projectId: 'basutei-1aba3',
    authDomain: 'basutei-1aba3.firebaseapp.com',
    storageBucket: 'basutei-1aba3.firebasestorage.app',
    measurementId: 'G-SLXSKZT1FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsbNZx-DUaEurW9woT0vqi0J7pF7O0AFU',
    appId: '1:163576928903:android:93d52baf97939220b77622',
    messagingSenderId: '163576928903',
    projectId: 'basutei-1aba3',
    storageBucket: 'basutei-1aba3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp5AZ40ZgjRzyFuie48Qg4oJrWx1NEQwM',
    appId: '1:163576928903:ios:a2b71d98644bf6d8b77622',
    messagingSenderId: '163576928903',
    projectId: 'basutei-1aba3',
    storageBucket: 'basutei-1aba3.firebasestorage.app',
    iosBundleId: 'com.example.basutei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp5AZ40ZgjRzyFuie48Qg4oJrWx1NEQwM',
    appId: '1:163576928903:ios:a2b71d98644bf6d8b77622',
    messagingSenderId: '163576928903',
    projectId: 'basutei-1aba3',
    storageBucket: 'basutei-1aba3.firebasestorage.app',
    iosBundleId: 'com.example.basutei',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPuBKuNBJG9SfbUs3Hiu7AlqyUgDrly6M',
    appId: '1:163576928903:web:54e1b979c2a838acb77622',
    messagingSenderId: '163576928903',
    projectId: 'basutei-1aba3',
    authDomain: 'basutei-1aba3.firebaseapp.com',
    storageBucket: 'basutei-1aba3.firebasestorage.app',
    measurementId: 'G-LNFMKE0EGQ',
  );

}